[package]
name = "async-lambda-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.7"
serde = "1.0.136"
tokio = { version = "1", features = ["macros"] }
aws-sdk-s3 = "1.16.0"
humansize = "2.0.0"
aws_lambda_events = "0.5"
serde_json = "1.0"
aws-config = "1.1.6"